spring:
  datasource:
    url: jdbc:postgresql://192.168.0.5:5432/ubos-hr
    username: admin9971
    password: 'wUsvZTFM'
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
logging:
  level:
    root: debug
scheduling:
  cron: "* */1 * * * *"

server:
  port: 8181